// GENERATED LIST, but generated once and checked in on purpose: a test that discovers its own
// inputs by scanning a directory silently passes when the directory is empty. These are the corpus
// entries whose root layout is a single `vortex.flat` leaf and whose array tree uses only the
// twenty-three encodings Phase 1 decodes, so each one is decodable end to end without a layout
// reader.
//
// The two lists below partition those 195 single-flat-leaf entries exactly, which is the property
// that makes them worth checking in: an entry that moves from one to the other because a decoder
// landed has to be moved by hand, and an entry that belongs to neither is a corpus change nobody
// looked at.
namespace Vorticity.Tests.Arrays.Decoders.Canonical;

internal static class CorpusEntries
{
    /// <summary>
    /// The 137 corpus entries this build decodes on its own. 85 of them need only the fourteen
    /// canonical encodings; the other 52 also reach one of the nine compressed ones, and moved here
    /// from <see cref="UnsupportedCorpusEntries"/> when wave C2 was wired into
    /// <see cref="Vorticity.Arrays.ArrayDecoderTable"/>.
    /// </summary>
    internal static readonly string[] All =
    [
        "containers/all_null_i64_explicit_validity_r1025",
        "encodings/bool",
        "encodings/bool_bit_offset3",
        "encodings/bool_bit_offset3_r1",
        "encodings/bool_bit_offset3_r1023",
        "encodings/bool_bit_offset3_r1025",
        "encodings/bool_bit_offset7",
        "encodings/bool_bit_offset7_r1",
        "encodings/bool_bit_offset7_r1023",
        "encodings/bool_bit_offset7_r1025",
        "encodings/bool_bit_offset_straddle",
        "encodings/bool_bit_offset_straddle_r1",
        "encodings/bool_bit_offset_straddle_r1023",
        "encodings/bool_bit_offset_straddle_r1025",
        "encodings/bool_r1",
        "encodings/bool_r1023",
        "encodings/bool_r1025",
        "encodings/bytebool",
        "encodings/bytebool_r1",
        "encodings/bytebool_r1023",
        "encodings/bytebool_r1025",
        "encodings/chunked",
        "encodings/chunked_empty_chunks",
        "encodings/chunked_empty_chunks_r1",
        "encodings/chunked_empty_chunks_r1023",
        "encodings/chunked_empty_chunks_r1025",
        "encodings/chunked_one_chunk",
        "encodings/chunked_one_chunk_r1",
        "encodings/chunked_one_chunk_r1023",
        "encodings/chunked_one_chunk_r1025",
        "encodings/chunked_r1",
        "encodings/chunked_r1023",
        "encodings/chunked_r1025",
        "encodings/constant",
        "encodings/constant_r1",
        "encodings/constant_r1023",
        "encodings/constant_r1025",
        "encodings/decimal",
        "encodings/decimal_r1",
        "encodings/decimal_r1023",
        "encodings/decimal_r1025",
        "encodings/dict",
        "encodings/dict_nullable_codes",
        "encodings/dict_nullable_codes_r1",
        "encodings/dict_nullable_codes_r1023",
        "encodings/dict_nullable_codes_r1025",
        "encodings/dict_nullable_values_nonnull_codes",
        "encodings/dict_nullable_values_nonnull_codes_r1",
        "encodings/dict_nullable_values_nonnull_codes_r1023",
        "encodings/dict_nullable_values_nonnull_codes_r1025",
        "encodings/dict_r1",
        "encodings/dict_r1023",
        "encodings/dict_r1025",
        "encodings/dict_u64_codes",
        "encodings/dict_u64_codes_r1",
        "encodings/dict_u64_codes_r1023",
        "encodings/dict_u64_codes_r1025",
        "encodings/dict_u8_codes",
        "encodings/dict_u8_codes_r1",
        "encodings/dict_u8_codes_r1023",
        "encodings/dict_u8_codes_r1025",
        "encodings/ext",
        "encodings/ext_r1",
        "encodings/ext_r1023",
        "encodings/ext_r1025",
        "encodings/fastlanes_bitpacked",
        "encodings/fastlanes_bitpacked_patched_no_chunk_offsets",
        "encodings/fastlanes_bitpacked_r1",
        "encodings/fastlanes_bitpacked_r1023",
        "encodings/fastlanes_bitpacked_r1025",
        "encodings/fastlanes_for",
        "encodings/fastlanes_for_r1",
        "encodings/fastlanes_for_r1023",
        "encodings/fastlanes_for_r1025",
        "encodings/fastlanes_rle",
        "encodings/fastlanes_rle_r1",
        "encodings/fastlanes_rle_r1023",
        "encodings/fastlanes_rle_r1025",
        "encodings/fixed_size_list",
        "encodings/fixed_size_list_r1",
        "encodings/fixed_size_list_r1023",
        "encodings/fixed_size_list_r1025",
        "encodings/list",
        "encodings/list_r1",
        "encodings/list_r1023",
        "encodings/list_r1025",
        "encodings/listview",
        "encodings/listview_r1",
        "encodings/listview_r1023",
        "encodings/listview_r1025",
        "encodings/masked",
        "encodings/masked_all_invalid",
        "encodings/masked_all_invalid_r1",
        "encodings/masked_all_invalid_r1023",
        "encodings/masked_all_invalid_r1025",
        "encodings/masked_all_valid",
        "encodings/masked_all_valid_r1",
        "encodings/masked_all_valid_r1023",
        "encodings/masked_all_valid_r1025",
        "encodings/masked_r1",
        "encodings/masked_r1023",
        "encodings/masked_r1025",
        "encodings/null",
        "encodings/null_r1",
        "encodings/null_r1023",
        "encodings/null_r1025",
        "encodings/primitive",
        "encodings/primitive_r1",
        "encodings/primitive_r1023",
        "encodings/primitive_r1025",
        "encodings/runend",
        "encodings/runend_r1",
        "encodings/runend_r1023",
        "encodings/runend_r1025",
        "encodings/sequence",
        "encodings/sequence_r1",
        "encodings/sequence_r1023",
        "encodings/sequence_r1025",
        "encodings/sparse",
        "encodings/sparse_r1023",
        "encodings/sparse_r1025",
        "encodings/struct",
        "encodings/struct_r1",
        "encodings/struct_r1023",
        "encodings/struct_r1025",
        "encodings/varbin",
        "encodings/varbin_r1",
        "encodings/varbin_r1023",
        "encodings/varbin_r1025",
        "encodings/varbinview",
        "encodings/varbinview_r1",
        "encodings/varbinview_r1023",
        "encodings/varbinview_r1025",
        "encodings/zigzag",
        "encodings/zigzag_r1",
        "encodings/zigzag_r1023",
        "encodings/zigzag_r1025",
    ];
}

internal static class UnsupportedCorpusEntries
{
    /// <summary>
    /// The single-flat-leaf corpus entries whose array tree still reaches an encoding this build
    /// does not implement - alp, alprd, datetimeparts, fastlanes.delta, fsst, map, onpair,
    /// parquet_variant, pco, variant and zstd_buffers. The list shrinks as Phase 2 lands.
    /// Decoding one must raise VortexUnsupportedException naming the id - never a wrong value, an
    /// out-of-bounds read or a different exception type (contract §2.3).
    /// </summary>
    internal static readonly string[] All =
    [
        "encodings/alp",
        "encodings/alp_no_patches",
        "encodings/alp_no_patches_r1",
        "encodings/alp_no_patches_r1023",
        "encodings/alp_no_patches_r1025",
        "encodings/alp_patched_no_chunk_offsets",
        "encodings/alp_r1",
        "encodings/alp_r1023",
        "encodings/alp_r1025",
        "encodings/alprd",
        "encodings/alprd_r1",
        "encodings/alprd_r1023",
        "encodings/alprd_r1025",
        "encodings/fastlanes_delta",
        "encodings/fastlanes_delta_r1",
        "encodings/fastlanes_delta_r1023",
        "encodings/fastlanes_delta_r1025",
        "encodings/fsst",
        "encodings/fsst_r1",
        "encodings/fsst_r1023",
        "encodings/fsst_r1025",
        "encodings/map",
        "encodings/map_r1",
        "encodings/map_r1023",
        "encodings/map_r1025",
        "encodings/onpair",
        "encodings/onpair_r1",
        "encodings/onpair_r1023",
        "encodings/onpair_r1025",
        "encodings/parquet_variant",
        "encodings/parquet_variant_r1",
        "encodings/parquet_variant_r1023",
        "encodings/parquet_variant_r1025",
        "encodings/pco",
        "encodings/pco_r1",
        "encodings/pco_r1023",
        "encodings/pco_r1025",
        "encodings/variant",
        "encodings/variant_r1",
        "encodings/variant_r1023",
        "encodings/variant_r1025",
        "encodings/zstd_buffers",
        "encodings/zstd_buffers_r1",
        "encodings/zstd_buffers_r1023",
        "encodings/zstd_buffers_r1025",
    ];
}
