using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Vorticity.Sealing;

/// <summary>
/// The data keys a session holds: the one its files are sealed under, drawn when it seals its first,
/// and the ones it unwrapped to read, cached so that the keyring is asked once per key.
/// </summary>
/// <remarks>
/// <para>
/// Every key handed out is lent under the cache's lock: the holder disposes it once it has derived
/// what it needs, and a key the cache let go is wiped when its last holder does. A key still being
/// unwrapped is never let go, so no holder can be lent a key already wiped. A session disposed wipes
/// what it holds, and what it was still waiting for as soon as it arrives.
/// </para>
/// <para>
/// The cache keeps at most <see cref="MaxKeys"/> keys, each for at most <see cref="MaxAge"/>,
/// starting points rather than measured values: past them, a key is unwrapped again, one call to the
/// keyring.
/// </para>
/// </remarks>
internal sealed class SessionKeys : IDisposable
{
    internal const int MaxKeys = 1024;

    internal static readonly TimeSpan MaxAge = TimeSpan.FromHours(1);

    private readonly VortexKeyring _keyring;
    private readonly TimeProvider _clock;
    private readonly Dictionary<string, Entry> _unwrapped = new Dictionary<string, Entry>(StringComparer.Ordinal);
    private readonly Queue<string> _order = new Queue<string>();
    private readonly object _gate = new object();
    private Task<DataKey>? _fileKeyPending;
    private DataKey? _fileKey;
    private bool _disposed;

    internal SessionKeys(VortexKeyring keyring, TimeProvider? clock = null)
    {
        _keyring = keyring;
        _clock = clock ?? TimeProvider.System;
    }

    /// <summary>How many times the keyring was asked to unwrap: what the cache saves is counted against it.</summary>
    internal int Unwraps { get; private set; }

    /// <summary>The key the session seals its files under, lent to the caller; generated by the first call.</summary>
    internal async ValueTask<DataKey> FileKeyAsync(CancellationToken cancellationToken)
    {
        Task<DataKey> pending;
        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_fileKey is { } held)
            {
                return held.Retain();
            }

            // Not the caller's token: a first writer cancelled must not leave the others a cancelled key.
            pending = _fileKeyPending ??= _keyring.GenerateAsync(ReadOnlyMemory<byte>.Empty, CancellationToken.None).AsTask();
        }

        DataKey key;
        try
        {
            key = await pending.WaitAsync(cancellationToken).ConfigureAwait(false);
        }
        catch when (pending.IsFaulted || pending.IsCanceled)
        {
            // A keyring that failed is asked again by the next file.
            lock (_gate)
            {
                if (ReferenceEquals(_fileKeyPending, pending))
                {
                    _fileKeyPending = null;
                }
            }

            throw;
        }

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            _fileKey ??= key;
            return key.Retain();
        }
    }

    /// <summary>The data key <paramref name="descriptor"/> names, lent to the caller: from the cache, or unwrapped once by the keyring.</summary>
    internal async ValueTask<DataKey> UnwrapAsync(SealDescriptor descriptor, CancellationToken cancellationToken)
    {
        string name = Name(descriptor);
        Entry entry;
        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_unwrapped.TryGetValue(name, out Entry? found) && (found.Key is null || _clock.GetUtcNow() - found.Added < MaxAge))
            {
                if (found.Key is { } held)
                {
                    return held.Retain();
                }

                entry = found;
            }
            else
            {
                if (found is not null)
                {
                    _unwrapped.Remove(name);
                    found.Key!.Dispose();
                }

                entry = new Entry(
                    _keyring.UnwrapAsync(descriptor.KeyId, descriptor.WrappedKey, descriptor.KeyContext, CancellationToken.None).AsTask(),
                    _clock.GetUtcNow());
                Unwraps++;
                _unwrapped[name] = entry;
                _order.Enqueue(name);
                Trim();
            }
        }

        DataKey key;
        try
        {
            key = await entry.Pending.WaitAsync(cancellationToken).ConfigureAwait(false);
        }
        catch when (entry.Pending.IsFaulted || entry.Pending.IsCanceled)
        {
            // A key the ring could not unwrap is not kept: the next open asks again, and says why again.
            lock (_gate)
            {
                if (_unwrapped.TryGetValue(name, out Entry? failed) && ReferenceEquals(failed, entry))
                {
                    _unwrapped.Remove(name);
                }
            }

            throw;
        }

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            entry.Key ??= key;
            return key.Retain();
        }
    }

    /// <summary>Wipes every key the session holds; keys still lent are wiped when their holders let them go.</summary>
    public void Dispose()
    {
        lock (_gate)
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            foreach (Entry entry in _unwrapped.Values)
            {
                Release(entry.Key, entry.Pending);
            }

            _unwrapped.Clear();
            _order.Clear();
            if (_fileKeyPending is { } pending)
            {
                Release(_fileKey, pending);
            }

            _fileKey = null;
            _fileKeyPending = null;
        }
    }

    /// <summary>Lets the oldest unwrapped keys go past the bound on their count; one still being unwrapped waits its turn.</summary>
    private void Trim()
    {
        int passes = _order.Count;
        while (_unwrapped.Count > MaxKeys && passes-- > 0 && _order.TryDequeue(out string? oldest))
        {
            if (!_unwrapped.TryGetValue(oldest, out Entry? entry))
            {
                continue;
            }

            if (entry.Key is null)
            {
                _order.Enqueue(oldest);
                continue;
            }

            _unwrapped.Remove(oldest);
            entry.Key.Dispose();
        }
    }

    /// <summary>Releases the session's hold on a key: at once if it arrived, or as soon as it does.</summary>
    private static void Release(DataKey? key, Task<DataKey> pending)
    {
        if (key is not null)
        {
            key.Dispose();
        }
        else
        {
            _ = DisposeWhenDoneAsync(pending);
        }

        static async Task DisposeWhenDoneAsync(Task<DataKey> pending)
        {
            try
            {
                // The keyring's own task, awaited without a context only to wipe its key once it arrives.
#pragma warning disable VSTHRD003
                DataKey arrived = await pending.ConfigureAwait(false);
#pragma warning restore VSTHRD003
                arrived.Dispose();
            }
            catch (Exception)
            {
                // A key that never arrived holds nothing to wipe, and its waiter reports the failure.
            }
        }
    }

    /// <summary>What names a wrapped key: the key that wrapped it, the wrapped bytes and the context.</summary>
    private static string Name(SealDescriptor descriptor) =>
        string.Concat(descriptor.KeyId, "\n", Convert.ToBase64String(descriptor.WrappedKey.Span), "\n", Convert.ToBase64String(descriptor.KeyContext.Span));

    /// <summary>A key being unwrapped, and once it is, the key, which the cache holds once.</summary>
    private sealed class Entry(Task<DataKey> pending, DateTimeOffset added)
    {
        internal Task<DataKey> Pending { get; } = pending;

        internal DateTimeOffset Added { get; } = added;

        internal DataKey? Key { get; set; }
    }
}
