<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Vorticity.Tests</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformCaptureOutput>false</TestingPlatformCaptureOutput>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Vorticity/Vorticity.csproj" />
    <ProjectReference Include="../../src/Vorticity.RowEncoding/Vorticity.RowEncoding.csproj" />
    <ProjectReference Include="../../src/Vorticity.Dataset/Vorticity.Dataset.csproj" />
  </ItemGroup>

</Project>
