using System.Collections.Generic;
using Microsoft.CodeAnalysis.CSharp;

namespace Vorticity.Generators;

/// <summary>Writes the C# of one record: the <c>IVortexRecord</c> implementation, <c>ColumnNames</c>, and the extension members.</summary>
internal static class RecordEmitter
{
    private const string Vortex = "global::Vorticity.";
    private const string Pool = "global::System.Buffers.ArrayPool<";
    private const string ContainsReferences = "global::System.Runtime.CompilerServices.RuntimeHelpers.IsReferenceOrContainsReferences<";

    public static string Emit(RecordModel model)
    {
        SourceWriter w = new SourceWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line("using global::Vorticity;");
        w.Line();
        if (model.Namespace is not null)
        {
            w.Open("namespace " + model.Namespace);
        }

        foreach (ContainerModel container in model.Containers)
        {
            w.Open("partial " + container.Keyword + " " + container.Name);
        }

        w.Open($"partial {model.Keyword} {model.Name} : {Vortex}IVortexRecord<{model.FullName}>");
        EmitSchema(w, model);
        w.Line();
        EmitReadRows(w, model);
        w.Line();
        EmitWriteRows(w, model);
        if (model.Names.EmitColumnNames)
        {
            w.Line();
            EmitColumnNames(w, model);
        }

        EmitHelpers(w, model);
        w.Close();
        foreach (ContainerModel unused in model.Containers)
        {
            w.Close();
        }

        if (model.ExtensionsName is not null)
        {
            w.Line();
            EmitExtensions(w, model);
        }

        if (model.Namespace is not null)
        {
            w.Close();
        }

        return w.ToString();
    }

    private static void EmitSchema(SourceWriter w, RecordModel model)
    {
        string interfaceName = $"{Vortex}IVortexRecord<{model.FullName}>";
        if (model.Names.ExplicitSchema)
        {
            w.Line($"private static readonly {Vortex}VortexSchema GeneratedVortexSchema =");
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Line($"public {(model.Names.HidesSchema ? "new " : string.Empty)}static {Vortex}VortexSchema Schema {{ get; }} =");
        }

        if (model.Members.Count == 0)
        {
            w.Line("    [];");
        }
        else
        {
            w.Line("[");
            foreach (MemberModel member in model.Members)
            {
                w.Line($"    ({SymbolDisplay.FormatLiteral(member.ColumnName, quote: true)}, {member.Value.Schema}),");
            }

            w.Line("];");
        }

        if (model.Names.ExplicitSchema)
        {
            w.Line();
            w.Line($"static {Vortex}VortexSchema {interfaceName}.Schema => GeneratedVortexSchema;");
        }
    }

    private static void EmitReadRows(SourceWriter w, RecordModel model)
    {
        string signature = $"void {(model.Names.ExplicitReadRows ? Vortex + "IVortexRecord<" + model.FullName + ">." : string.Empty)}ReadRows({Vortex}Columns<{model.FullName}> columns, global::System.Span<{model.FullName}> rows)";
        if (model.Names.ExplicitReadRows)
        {
            w.Open("static " + signature);
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Open((model.Names.HidesReadRows ? "public new static " : "public static ") + signature);
        }

        w.Line("int count = rows.Length;");
        List<(string Type, string Name)> temps = [];
        string[] values = new string[model.Members.Count];
        bool[] buffered = new bool[model.Members.Count];
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (member.Fill == MemberFill.Assignment)
            {
                continue;
            }

            ValueModel value = member.Value;
            if (value.IsNumber && !value.IsNullable)
            {
                w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values{k} = columns.Column<{value.ColumnType}>({k}).Values;");
                values[k] = value.Kind == ValueKind.Enum ? $"({value.MemberType})values{k}[i]" : $"values{k}[i]";
            }
            else
            {
                temps.Add((value.MemberType, "temp" + k));
                values[k] = $"temp{k}[i]";
                buffered[k] = true;
            }
        }

        foreach ((string type, string name) in temps)
        {
            w.Line($"{type}[] {name} = {Pool}{type}>.Shared.Rent(count);");
        }

        bool guarded = temps.Count > 0;
        if (guarded)
        {
            w.Open("try");
        }

        for (int k = 0; k < model.Members.Count; k++)
        {
            ValueModel value = model.Members[k].Value;
            if (!buffered[k])
            {
                continue;
            }

            if (value.Kind == ValueKind.Record && !value.IsNullable)
            {
                w.Line($"ReadNested(columns.Struct<{value.CoreType}>({k}), new global::System.Span<{value.CoreType}>(temp{k}, 0, count));");
            }
            else
            {
                EmitRead(w, value, k, $"temp{k}[i]");
            }

            w.Line();
        }

        EmitConstruction(w, model, values);
        if (guarded)
        {
            w.Close();
            w.Open("finally");
            foreach ((string type, string name) in temps)
            {
                w.Line($"{Pool}{type}>.Shared.Return({name}, {ContainsReferences}{type}>());");
            }

            w.Close();
        }

        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (member.Fill == MemberFill.Assignment)
            {
                w.Line();
                EmitRead(w, member.Value, k, $"rows[i].{RecordAnalysis.Escape(member.Name)}");
            }
        }

        bool nested = false;
        for (int k = 0; k < model.Members.Count; k++)
        {
            ValueModel value = model.Members[k].Value;
            nested |= value.Kind == ValueKind.Record;
            if (value.Kind == ValueKind.List)
            {
                w.Line();
                EmitReadList(w, value, "ReadList" + k);
            }
        }

        if (nested)
        {
            w.Line();
            w.Line($"static void ReadNested<TNested>({Vortex}Columns<TNested> columns, global::System.Span<TNested> rows)");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.ReadRows(columns, rows);");
        }

        w.Close();
    }

    private static void EmitConstruction(SourceWriter w, RecordModel model, string[] values)
    {
        List<string> arguments = [];
        if (model.HasConstructorArguments)
        {
            foreach (int member in model.ConstructorArguments)
            {
                arguments.Add(member < 0 ? "default!" : values[member]);
            }
        }

        List<string> initializers = [];
        for (int k = 0; k < model.Members.Count; k++)
        {
            if (model.Members[k].Fill == MemberFill.Initializer)
            {
                initializers.Add($"{RecordAnalysis.Escape(model.Members[k].Name)} = {values[k]},");
            }
        }

        w.Open("for (int i = 0; i < count; i++)");
        string creation = $"new {model.FullName}({string.Join(", ", arguments)})";
        if (initializers.Count == 0)
        {
            w.Line($"rows[i] = {creation};");
        }
        else
        {
            w.Line($"rows[i] = {creation}");
            w.Line("{");
            foreach (string initializer in initializers)
            {
                w.Line("    " + initializer);
            }

            w.Line("};");
        }

        w.Close();
    }

    /// <summary>Fills <paramref name="target"/>, an expression of row <c>i</c>, from member <paramref name="k"/>'s column, for every row.</summary>
    private static void EmitRead(SourceWriter w, ValueModel value, int k, string target)
    {
        w.Line("{");
        w.Indent();
        switch (value.Kind)
        {
            case ValueKind.Record:
                EmitReadNested(w, value, k, target);
                break;
            case ValueKind.List:
                w.Line($"{Vortex}Column<{value.ColumnType}> column = columns.Column<{value.ColumnType}>({k});");
                w.Line($"{Vortex}Column<{value.Element!.ColumnType}> elements = column.Elements;");
                Loop(w, value.IsNullable
                    ? $"{target} = column.IsValid(i) ? new global::System.ReadOnlyMemory<{value.Element.MemberType}>(ReadList{k}(column, elements, i)) : default({value.MemberType});"
                    : $"{target} = ReadList{k}(column, elements, i);");
                break;
            default:
                if (value.IsNumber && !value.IsNullable)
                {
                    w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values = columns.Column<{value.ColumnType}>({k}).Values;");
                    Loop(w, value.Kind == ValueKind.Enum ? $"{target} = ({value.MemberType})values[i];" : $"{target} = values[i];");
                }
                else
                {
                    w.Line($"{Vortex}Column<{value.ColumnType}> column = columns.Column<{value.ColumnType}>({k});");
                    Loop(w, $"{target} = {ScalarRead(value, "column", "i")};");
                }

                break;
        }

        w.Close();
    }

    /// <summary>
    /// Reads member <paramref name="k"/>'s nested record into a rented temporary, then copies it to
    /// <paramref name="target"/>; a nullable one is null where the struct column is, and is copied
    /// without a check when that column has no null.
    /// </summary>
    private static void EmitReadNested(SourceWriter w, ValueModel value, int k, string target)
    {
        string nested = value.CoreType;
        if (value.IsNullable)
        {
            w.Line($"{Vortex}Columns<{nested}> nestedColumns = columns.Struct<{nested}>({k});");
        }

        w.Line($"{nested}[] nested = {Pool}{nested}>.Shared.Rent(count);");
        w.Open("try");
        if (!value.IsNullable)
        {
            w.Line($"ReadNested(columns.Struct<{nested}>({k}), new global::System.Span<{nested}>(nested, 0, count));");
            Loop(w, $"{target} = nested[i];");
        }
        else
        {
            w.Line($"ReadNested(nestedColumns, new global::System.Span<{nested}>(nested, 0, count));");
            w.Open("if (nestedColumns.IsAllValid)");
            Loop(w, $"{target} = nested[i];");
            w.Close();
            w.Open("else");
            w.Line("global::System.ReadOnlySpan<ulong> valid = nestedColumns.ValidityWords;");
            Loop(w, $"{target} = ((valid[i >> 6] >> (i & 63)) & 1UL) != 0 ? nested[i] : default({value.MemberType});");
            w.Close();
        }

        w.Close();
        w.Open("finally");
        w.Line($"{Pool}{nested}>.Shared.Return(nested, {ContainsReferences}{nested}>());");
        w.Close();
    }

    private static void Loop(SourceWriter w, string statement)
    {
        w.Open("for (int i = 0; i < count; i++)");
        w.Line(statement);
        w.Close();
    }

    /// <summary>The value of row <paramref name="index"/> of <paramref name="column"/>, a column of a scalar, an enum or an extension.</summary>
    private static string ScalarRead(ValueModel value, string column, string index)
    {
        if (value.Kind == ValueKind.Enum)
        {
            return $"({value.MemberType}){column}[{index}]";
        }

        return value.Scalar switch
        {
            ScalarKind.Utf8 when value.Kind == ValueKind.Scalar => $"{column}.GetString({index})" + (value.IsNullable ? string.Empty : "!"),
            ScalarKind.Binary when value.Kind == ValueKind.Scalar => value.IsNullable
                ? $"{column}.IsValid({index}) ? new global::System.ReadOnlyMemory<byte>({column}[{index}].ToArray()) : default(global::System.ReadOnlyMemory<byte>?)"
                : $"new global::System.ReadOnlyMemory<byte>({column}[{index}].ToArray())",
            _ => $"{column}[{index}]",
        };
    }

    /// <summary>A local function that copies one list of <paramref name="list"/>'s column into a new array.</summary>
    private static void EmitReadList(SourceWriter w, ValueModel list, string name)
    {
        ValueModel element = list.Element!;
        w.Open($"static {element.MemberType}[] {name}({Vortex}Column<{list.ColumnType}> column, {Vortex}Column<{element.ColumnType}> elements, int row)");
        w.Line("(int offset, int length) = column[row].GetOffsetAndLength(elements.Length);");
        if (element.IsNumber && !element.IsNullable && element.Kind == ValueKind.Scalar)
        {
            w.Line("return elements.Values.Slice(offset, length).ToArray();");
            w.Close();
            return;
        }

        w.Open("if (length == 0)");
        w.Line("return [];");
        w.Close();
        w.Line();
        w.Line($"{element.MemberType}[] list = new {element.MemberType}[length];");
        string read;
        if (element.IsNumber && !element.IsNullable)
        {
            w.Line($"global::System.ReadOnlySpan<{element.UnderlyingType}> values = elements.Values;");
            read = $"({element.MemberType})values[offset + j]";
        }
        else if (element.Kind == ValueKind.List)
        {
            w.Line($"{Vortex}Column<{element.Element!.ColumnType}> inner = elements.Elements;");
            string call = $"{name}_(elements, inner, offset + j)";
            read = element.IsNullable
                ? $"elements.IsValid(offset + j) ? new global::System.ReadOnlyMemory<{element.Element.MemberType}>({call}) : default({element.MemberType})"
                : call;
        }
        else
        {
            read = ScalarRead(element, "elements", "offset + j");
        }

        w.Open("for (int j = 0; j < length; j++)");
        w.Line($"list[j] = {read};");
        w.Close();
        w.Line();
        w.Line("return list;");
        w.Close();
        if (element.Kind == ValueKind.List)
        {
            w.Line();
            EmitReadList(w, element, name + "_");
        }
    }

    private static void EmitWriteRows(SourceWriter w, RecordModel model)
    {
        string signature = $"void {(model.Names.ExplicitWriteRows ? Vortex + "IVortexRecord<" + model.FullName + ">." : string.Empty)}WriteRows({Vortex}ColumnsBuilder<{model.FullName}> builder, global::System.ReadOnlySpan<{model.FullName}> rows)";
        if (model.Names.ExplicitWriteRows)
        {
            w.Open("static " + signature);
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Open((model.Names.HidesWriteRows ? "public new static " : "public static ") + signature);
        }

        w.Line("int count = rows.Length;");
        bool nested = false;
        int unique = 0;
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            string source = "rows[i]." + RecordAnalysis.Escape(member.Name);
            w.Line("{");
            w.Indent();
            if (value.Kind == ValueKind.Record)
            {
                nested = true;
                EmitWriteNested(w, value, k, source);
            }
            else if (value.IsNumber && !value.IsNullable)
            {
                w.Line($"{Vortex}ColumnBuilder<{value.ColumnType}> column = builder.Column<{value.ColumnType}>({k});");
                w.Line($"global::System.Span<{value.ColumnType}> span = column.GetSpan(count);");
                Loop(w, value.Kind == ValueKind.Enum ? $"span[i] = ({value.UnderlyingType}){source};" : $"span[i] = {source};");
                w.Line();
                w.Line("column.Advance(count);");
            }
            else
            {
                w.Line($"{Vortex}ColumnBuilder<{value.WriteColumnType}> column = builder.Column<{value.WriteColumnType}>({k});");
                w.Open("for (int i = 0; i < count; i++)");
                EmitWriteValue(w, value, "column", source, ref unique);
                w.Close();
            }

            w.Close();
            if (k < model.Members.Count - 1 || nested)
            {
                w.Line();
            }
        }

        if (nested)
        {
            w.Line($"static void WriteNested<TNested>({Vortex}ColumnsBuilder<TNested> builder, global::System.ReadOnlySpan<TNested> rows)");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.WriteRows(builder, rows);");
        }

        w.Close();
    }

    private static void EmitWriteNested(SourceWriter w, ValueModel value, int k, string source)
    {
        string nested = value.CoreType;
        string span = $"new global::System.ReadOnlySpan<{nested}>(nested, 0, ";
        if (value.IsNullable)
        {
            w.Line($"{Vortex}ColumnsBuilder<{nested}> nestedBuilder = builder.Struct<{nested}>({k});");
        }

        w.Line($"{nested}[] nested = {Pool}{nested}>.Shared.Rent(count);");
        w.Open("try");
        if (value.IsNullable)
        {
            w.Line("int run = 0;");
            w.Open("for (int i = 0; i < count; i++)");
            w.Open($"if ({source} is {{ }} value)");
            w.Line("nested[run++] = value;");
            w.Line("continue;");
            w.Close();
            w.Line();
            w.Open("if (run > 0)");
            w.Line($"WriteNested(nestedBuilder, {span}run));");
            w.Line("run = 0;");
            w.Close();
            w.Line();
            w.Line("nestedBuilder.AppendNull();");
            w.Close();
            w.Line();
            w.Open("if (run > 0)");
            w.Line($"WriteNested(nestedBuilder, {span}run));");
            w.Close();
        }
        else
        {
            Loop(w, $"nested[i] = {source};");
            w.Line();
            w.Line($"WriteNested(builder.Struct<{nested}>({k}), {span}count));");
        }

        w.Close();
        w.Open("finally");
        w.Line($"{Pool}{nested}>.Shared.Return(nested, {ContainsReferences}{nested}>());");
        w.Close();
    }

    /// <summary>Appends <paramref name="source"/>, one value of <paramref name="value"/>'s type, to <paramref name="builder"/>.</summary>
    private static void EmitWriteValue(SourceWriter w, ValueModel value, string builder, string source, ref int unique)
    {
        if (value.Kind == ValueKind.Enum)
        {
            w.Line($"{builder}.Append(({value.ColumnType}){source});");
            return;
        }

        switch (value.Kind == ValueKind.List ? (ScalarKind?)null : value.Scalar)
        {
            case ScalarKind.Utf8 when value.IsNullable:
                string text = "text" + unique++;
                IfPresent(w, builder, source, text, $"{builder}.Append(global::System.MemoryExtensions.AsSpan({text}));");
                return;
            case ScalarKind.Utf8:
                w.Line($"{builder}.Append(global::System.MemoryExtensions.AsSpan({source}));");
                return;
            case ScalarKind.Binary when value.IsNullable:
                string bytes = "bytes" + unique++;
                IfPresent(w, builder, source, bytes, $"{builder}.Append({bytes}.Span);");
                return;
            case ScalarKind.Binary:
                w.Line($"{builder}.Append({source}.Span);");
                return;
            case null:
                break;
            default:
                w.Line($"{builder}.Append({source});");
                return;
        }

        if (value.IsNullable)
        {
            string list = "list" + unique++;
            w.Open($"if ({source} is {{ }} {list})");
            EmitWriteList(w, value, builder, list, ref unique);
            w.Close();
            w.Open("else");
            w.Line($"{builder}.AppendNull();");
            w.Close();
            return;
        }

        EmitWriteList(w, value, builder, source, ref unique);
    }

    private static void IfPresent(SourceWriter w, string builder, string source, string name, string append)
    {
        w.Open($"if ({source} is {{ }} {name})");
        w.Line(append);
        w.Close();
        w.Open("else");
        w.Line($"{builder}.AppendNull();");
        w.Close();
    }

    private static void EmitWriteList(SourceWriter w, ValueModel list, string builder, string source, ref int unique)
    {
        if (list.ElementsAsDeclared)
        {
            w.Line($"{builder}.Append({source}.Span);");
            return;
        }

        ValueModel element = list.Element!;
        string elements = "elements" + unique++;
        string item = "item" + unique++;
        w.Line($"{builder}.BeginList();");
        w.Line($"var {elements} = {builder}.Elements;");
        w.Open($"foreach ({element.MemberType} {item} in {source}.Span)");
        EmitWriteValue(w, element, elements, item, ref unique);
        w.Close();
        w.Line();
        w.Line($"{builder}.EndList();");
    }

    private static void EmitColumnNames(SourceWriter w, RecordModel model)
    {
        w.Line("/// <summary>The name of each member's column, for the options that name a column.</summary>");
        w.Open($"public {(model.Names.HidesColumnNames ? "new " : string.Empty)}static class ColumnNames");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (k > 0)
            {
                w.Line();
            }

            w.Line($"/// <summary>The column of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line($"public const string {RecordAnalysis.Escape(member.Name)} = {SymbolDisplay.FormatLiteral(member.ColumnName, quote: true)};");
        }

        w.Close();
    }

    private static void EmitHelpers(SourceWriter w, RecordModel model)
    {
        if (model.NeedsSchemaHelper)
        {
            w.Line();
            w.Line($"private static {Vortex}VortexSchema VortexSchemaOf<TNested>()");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.Schema;");
        }

        if (model.NeedsExtensionHelper)
        {
            w.Line();
            w.Line($"private static {Vortex}VortexType VortexExtensionTypeOf<TExtension>()");
            w.Line($"    where TExtension : {Vortex}IVortexExtension<TExtension> => {Vortex}VortexType.Extension(TExtension.Id, TExtension.StorageType);");
        }
    }

    private static void EmitExtensions(SourceWriter w, RecordModel model)
    {
        GeneratedNames names = model.Names;
        string record = model.FullName;
        w.Line($"/// <summary>The members of <see cref=\"{record}\"/> as symbols in a scan's lambdas, as columns of a delivered batch, and as builders of a writer.</summary>");
        w.Open($"{model.ExtensionsAccessibility} static class {model.ExtensionsName}");

        w.Open($"extension({Vortex}Probe<{record}> {names.ProbeName})");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            Separate(w, k);
            w.Line($"/// <summary>The symbol of <see cref=\"{Cref(member)}\"/>, for the lambdas of a scan.</summary>");
            w.Line(value.Kind == ValueKind.Record
                ? $"public {Vortex}Probe<{value.CoreType}> {RecordAnalysis.Escape(member.Name)} => {names.ProbeName}.Struct<{value.CoreType}>({k});"
                : $"public {Vortex}Sym<{value.SymbolType}> {RecordAnalysis.Escape(member.Name)} => {names.ProbeName}.Column<{value.SymbolType}>({k});");
        }

        w.Close();
        w.Line();

        w.Open($"extension({Vortex}Columns<{record}> {names.ColumnsName})");
        List<string> parameters = [];
        List<string> assignments = [];
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            string type = ColumnsType(member.Value);
            string access = ColumnsAccess(member.Value, names.ColumnsName, k);
            Separate(w, k);
            w.Line($"/// <summary>The column of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line($"public {type} {RecordAnalysis.Escape(member.Name)} => {access};");
            parameters.Add($"out {type} {names.DeconstructNames[k]}");
            assignments.Add($"{names.DeconstructNames[k]} = {access};");
        }

        w.Line();
        w.Line("/// <summary>Every member's column, in order, for <c>await foreach (var (...) in scan)</c>.</summary>");
        w.Open($"public void Deconstruct({string.Join(", ", parameters)})");
        foreach (string assignment in assignments)
        {
            w.Line(assignment);
        }

        w.Close();
        w.Close();
        w.Line();

        w.Open($"extension({Vortex}ColumnsBuilder<{record}> {names.BuilderName})");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            Separate(w, k);
            w.Line($"/// <summary>The builder of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line(value.Kind == ValueKind.Record
                ? $"public {Vortex}ColumnsBuilder<{value.CoreType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.Struct<{value.CoreType}>({k});"
                : $"public {Vortex}ColumnBuilder<{value.ColumnType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.Column<{value.ColumnType}>({k});");
        }

        w.Close();
        w.Close();
    }

    private static string ColumnsType(ValueModel value) =>
        value.Kind == ValueKind.Record ? $"{Vortex}Columns<{value.CoreType}>" : $"{Vortex}Column<{value.ColumnType}>";

    private static string ColumnsAccess(ValueModel value, string receiver, int k) =>
        value.Kind == ValueKind.Record ? $"{receiver}.Struct<{value.CoreType}>({k})" : $"{receiver}.Column<{value.ColumnType}>({k})";

    private static void Separate(SourceWriter w, int k)
    {
        if (k > 0)
        {
            w.Line();
        }
    }

    private static string Cref(MemberModel member) => member.DeclaringType + "." + RecordAnalysis.Escape(member.Name);
}
