using System.Collections.Generic;
using Microsoft.CodeAnalysis.CSharp;

namespace Vorticity.Generators;

/// <summary>Writes the C# of one record: the <c>IVortexRecord</c> implementation, <c>ColumnNames</c>, and the extension members.</summary>
internal static class RecordEmitter
{
    private const string Vortex = "global::Vorticity.";
    private const string Pool = "global::System.Buffers.ArrayPool<";
    private const string ContainsReferences = "global::System.Runtime.CompilerServices.RuntimeHelpers.IsReferenceOrContainsReferences<";

    public static string Emit(RecordModel model)
    {
        SourceWriter w = new SourceWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line("using global::Vorticity;");
        w.Line();
        if (model.Namespace is not null)
        {
            w.Open("namespace " + model.Namespace);
        }

        foreach (ContainerModel container in model.Containers)
        {
            w.Open("partial " + container.Keyword + " " + container.Name);
        }

        w.Open($"partial {model.Keyword} {model.Name} : {Vortex}IVortexRecord<{model.FullName}>");
        EmitSchema(w, model);
        w.Line();
        EmitReadRows(w, model);
        w.Line();
        EmitWriteRows(w, model);
        if (model.Names.EmitColumnNames)
        {
            w.Line();
            EmitColumnNames(w, model);
        }

        EmitHelpers(w, model);
        w.Close();
        foreach (ContainerModel unused in model.Containers)
        {
            w.Close();
        }

        if (model.ExtensionsName is not null)
        {
            w.Line();
            EmitExtensions(w, model);
        }

        if (model.Namespace is not null)
        {
            w.Close();
        }

        return w.ToString();
    }

    private static void EmitSchema(SourceWriter w, RecordModel model)
    {
        string interfaceName = $"{Vortex}IVortexRecord<{model.FullName}>";
        if (model.Names.ExplicitSchema)
        {
            w.Line($"private static readonly {Vortex}VortexSchema GeneratedVortexSchema =");
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Line($"public {(model.Names.HidesSchema ? "new " : string.Empty)}static {Vortex}VortexSchema Schema {{ get; }} =");
        }

        if (model.Members.Count == 0)
        {
            w.Line("    [];");
        }
        else
        {
            w.Line("[");
            foreach (MemberModel member in model.Members)
            {
                w.Line($"    ({SymbolDisplay.FormatLiteral(member.ColumnName, quote: true)}, {member.Value.Schema}),");
            }

            w.Line("];");
        }

        if (model.Names.ExplicitSchema)
        {
            w.Line();
            w.Line($"static {Vortex}VortexSchema {interfaceName}.Schema => GeneratedVortexSchema;");
        }
    }

    private static void EmitReadRows(SourceWriter w, RecordModel model)
    {
        string signature = $"void {(model.Names.ExplicitReadRows ? Vortex + "IVortexRecord<" + model.FullName + ">." : string.Empty)}ReadRows({Vortex}Columns<{model.FullName}> columns, global::System.Span<{model.FullName}> rows)";
        if (model.Names.ExplicitReadRows)
        {
            w.Open("static " + signature);
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Open((model.Names.HidesReadRows ? "public new static " : "public static ") + signature);
        }

        w.Line("int count = rows.Length;");
        List<(string Type, string Name)> temps = [];
        string[] values = new string[model.Members.Count];
        bool[] buffered = new bool[model.Members.Count];
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (member.Fill == MemberFill.Assignment)
            {
                continue;
            }

            ValueModel value = member.Value;
            if (value.IsNumber && !value.IsNullable)
            {
                w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values{k} = columns.Column<{value.ColumnType}>({k}).Values;");
                values[k] = value.Kind == ValueKind.Enum ? $"({value.MemberType})values{k}[i]" : $"values{k}[i]";
            }
            else if (value.IsNumber)
            {
                // The values and the validity words once per column, and a bit test per row: the
                // indexer of a nullable column resolves the column again on every call.
                w.Line($"{Vortex}Column<{value.ColumnType}> column{k} = columns.Column<{value.ColumnType}>({k});");
                w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values{k} = column{k}.Values;");
                w.Line($"bool allValid{k} = column{k}.IsAllValid;");
                w.Line($"global::System.ReadOnlySpan<ulong> valid{k} = column{k}.ValidityWords;");
                string read = value.Kind == ValueKind.Enum ? $"({value.MemberType})values{k}[i]" : $"values{k}[i]";
                values[k] = $"(allValid{k} || ((valid{k}[i >> 6] >> (i & 63)) & 1UL) != 0 ? {read} : default({value.MemberType}))";
            }
            else
            {
                temps.Add((value.MemberType, "temp" + k));
                values[k] = $"temp{k}[i]";
                buffered[k] = true;
            }
        }

        foreach ((string type, string name) in temps)
        {
            w.Line($"{type}[] {name} = {Pool}{type}>.Shared.Rent(count);");
        }

        bool guarded = temps.Count > 0;
        if (guarded)
        {
            w.Open("try");
        }

        for (int k = 0; k < model.Members.Count; k++)
        {
            ValueModel value = model.Members[k].Value;
            if (!buffered[k])
            {
                continue;
            }

            if (value.Kind == ValueKind.Record && !value.IsNullable)
            {
                w.Line($"ReadNested(columns.Struct<{value.CoreType}>({k}), new global::System.Span<{value.CoreType}>(temp{k}, 0, count));");
            }
            else
            {
                EmitRead(w, value, k, $"temp{k}[i]", buffer: $"temp{k}");
            }

            w.Line();
        }

        EmitConstruction(w, model, values);
        if (guarded)
        {
            w.Close();
            w.Open("finally");
            foreach ((string type, string name) in temps)
            {
                w.Line($"{Pool}{type}>.Shared.Return({name}, {ContainsReferences}{type}>());");
            }

            w.Close();
        }

        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (member.Fill == MemberFill.Assignment)
            {
                w.Line();
                EmitRead(w, member.Value, k, $"rows[i].{RecordAnalysis.Escape(member.Name)}");
            }
        }

        bool nested = false;
        for (int k = 0; k < model.Members.Count; k++)
        {
            ValueModel value = model.Members[k].Value;
            nested |= value.Kind == ValueKind.Record || value.IsRecordList;
            if (value.IsRecordList)
            {
                w.Line();
                EmitRecordListContainer(w, value, "RecordList" + k);
            }
            else if (value.Kind == ValueKind.List)
            {
                w.Line();
                EmitReadList(w, value, "ReadList" + k);
            }
        }

        if (nested)
        {
            w.Line();
            w.Line($"static void ReadNested<TNested>({Vortex}Columns<TNested> columns, global::System.Span<TNested> rows)");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.ReadRows(columns, rows);");
        }

        w.Close();
    }

    private static void EmitConstruction(SourceWriter w, RecordModel model, string[] values)
    {
        List<string> arguments = [];
        if (model.HasConstructorArguments)
        {
            foreach (int member in model.ConstructorArguments)
            {
                arguments.Add(member < 0 ? "default!" : values[member]);
            }
        }

        List<string> initializers = [];
        for (int k = 0; k < model.Members.Count; k++)
        {
            if (model.Members[k].Fill == MemberFill.Initializer)
            {
                initializers.Add($"{RecordAnalysis.Escape(model.Members[k].Name)} = {values[k]},");
            }
        }

        w.Open("for (int i = 0; i < count; i++)");
        string creation = $"new {model.FullName}({string.Join(", ", arguments)})";
        if (initializers.Count == 0)
        {
            w.Line($"rows[i] = {creation};");
        }
        else
        {
            w.Line($"rows[i] = {creation}");
            w.Line("{");
            foreach (string initializer in initializers)
            {
                w.Line("    " + initializer);
            }

            w.Line("};");
        }

        w.Close();
    }

    /// <summary>Fills <paramref name="target"/>, an expression of row <c>i</c>, from member <paramref name="k"/>'s column, for every row.</summary>
    /// <param name="w">The writer.</param>
    /// <param name="value">The member's type.</param>
    /// <param name="k">The member's position.</param>
    /// <param name="target">The expression of row <c>i</c> to fill.</param>
    /// <param name="buffer">The array <paramref name="target"/> indexes, when it is one: a column then copies itself into it whole.</param>
    private static void EmitRead(SourceWriter w, ValueModel value, int k, string target, string? buffer = null)
    {
        w.Line("{");
        w.Indent();
        switch (value.Kind)
        {
            case ValueKind.Record:
                EmitReadNested(w, value, k, target);
                break;
            case ValueKind.List when value.IsRecordList:
                EmitReadRecordList(w, value, k, target);
                break;
            case ValueKind.Map:
                EmitReadMap(w, value, k, target);
                break;
            case ValueKind.List:
                w.Line($"{Vortex}Column<{value.ColumnType}> column = columns.Column<{value.ColumnType}>({k});");
                w.Line($"{Vortex}Column<{value.Element!.ColumnType}> elements = column.Elements;");
                string list = Contain(value, $"ReadList{k}(column, elements, i)");
                Loop(w, value.IsNullable
                    ? $"{target} = column.IsValid(i) ? {list} : default({value.MemberType});"
                    : $"{target} = {list};");
                break;
            default:
                if (value.IsNumber && !value.IsNullable)
                {
                    w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values = columns.Column<{value.ColumnType}>({k}).Values;");
                    Loop(w, value.Kind == ValueKind.Enum ? $"{target} = ({value.MemberType})values[i];" : $"{target} = values[i];");
                }
                else if (value.IsNumber)
                {
                    w.Line($"{Vortex}Column<{value.ColumnType}> column = columns.Column<{value.ColumnType}>({k});");
                    w.Line($"global::System.ReadOnlySpan<{value.UnderlyingType}> values = column.Values;");
                    string read = value.Kind == ValueKind.Enum ? $"({value.MemberType})values[i]" : "values[i]";
                    w.Open("if (column.IsAllValid)");
                    Loop(w, $"{target} = {read};");
                    w.Close();
                    w.Open("else");
                    w.Line("global::System.ReadOnlySpan<ulong> valid = column.ValidityWords;");
                    Loop(w, $"{target} = ((valid[i >> 6] >> (i & 63)) & 1UL) != 0 ? {read} : default({value.MemberType});");
                    w.Close();
                }
                else if (Copies(value) && buffer is not null)
                {
                    // The column copies itself whole: its node resolved once, a conversion per row.
                    w.Line($"columns.Column<{value.ColumnType}>({k}).CopyTo(new global::System.Span<{value.MemberType}>({buffer}, 0, count));");
                }
                else if (Copies(value))
                {
                    w.Line($"{value.MemberType}[] copy = {Pool}{value.MemberType}>.Shared.Rent(count);");
                    w.Open("try");
                    w.Line($"columns.Column<{value.ColumnType}>({k}).CopyTo(new global::System.Span<{value.MemberType}>(copy, 0, count));");
                    Loop(w, $"{target} = copy[i];");
                    w.Close();
                    w.Open("finally");
                    w.Line($"{Pool}{value.MemberType}>.Shared.Return(copy, {ContainsReferences}{value.MemberType}>());");
                    w.Close();
                }
                else
                {
                    w.Line($"{Vortex}Column<{value.ColumnType}> column = columns.Column<{value.ColumnType}>({k});");
                    Loop(w, $"{target} = {ScalarRead(value, "column", "i")};");
                }

                break;
        }

        w.Close();
    }

    /// <summary>Whether a column of <paramref name="value"/> copies every row at once through <c>CopyTo</c>.</summary>
    private static bool Copies(ValueModel value) =>
        value.Kind == ValueKind.Scalar
        && value.Scalar is ScalarKind.Bool or ScalarKind.Utf8 or ScalarKind.Decimal or ScalarKind.WideDecimal
            or ScalarKind.Date or ScalarKind.Time or ScalarKind.Timestamp or ScalarKind.ZonedTimestamp or ScalarKind.Uuid
            or ScalarKind.Duration or ScalarKind.Int128 or ScalarKind.UInt128 or ScalarKind.BigInteger;

    /// <summary>
    /// Reads member <paramref name="k"/>'s nested record into a rented temporary, then copies it to
    /// <paramref name="target"/>; a nullable one is null where the struct column is, and is copied
    /// without a check when that column has no null.
    /// </summary>
    private static void EmitReadNested(SourceWriter w, ValueModel value, int k, string target)
    {
        string nested = value.CoreType;
        if (value.IsNullable)
        {
            w.Line($"{Vortex}Columns<{nested}> nestedColumns = columns.Struct<{nested}>({k});");
        }

        w.Line($"{nested}[] nested = {Pool}{nested}>.Shared.Rent(count);");
        w.Open("try");
        if (!value.IsNullable)
        {
            w.Line($"ReadNested(columns.Struct<{nested}>({k}), new global::System.Span<{nested}>(nested, 0, count));");
            Loop(w, $"{target} = nested[i];");
        }
        else
        {
            w.Line($"ReadNested(nestedColumns, new global::System.Span<{nested}>(nested, 0, count));");
            w.Open("if (nestedColumns.IsAllValid)");
            Loop(w, $"{target} = nested[i];");
            w.Close();
            w.Open("else");
            w.Line("global::System.ReadOnlySpan<ulong> valid = nestedColumns.ValidityWords;");
            Loop(w, $"{target} = ((valid[i >> 6] >> (i & 63)) & 1UL) != 0 ? nested[i] : default({value.MemberType});");
            w.Close();
        }

        w.Close();
        w.Open("finally");
        w.Line($"{Pool}{nested}>.Shared.Return(nested, {ContainsReferences}{nested}>());");
        w.Close();
    }

    private static void Loop(SourceWriter w, string statement)
    {
        w.Open("for (int i = 0; i < count; i++)");
        w.Line(statement);
        w.Close();
    }

    /// <summary>The value of row <paramref name="index"/> of <paramref name="column"/>, a column of a scalar, an enum or an extension.</summary>
    private static string ScalarRead(ValueModel value, string column, string index)
    {
        if (value.Kind == ValueKind.Enum)
        {
            return $"({value.MemberType}){column}[{index}]";
        }

        return value.Scalar switch
        {
            ScalarKind.Utf8 when value.Kind == ValueKind.Scalar => $"{column}.GetString({index})" + (value.IsNullable ? string.Empty : "!"),
            ScalarKind.Binary when value.Kind == ValueKind.Scalar => value.IsNullable
                ? $"{column}.IsValid({index}) ? {Bytes(value, $"{column}[{index}]")} : default({value.MemberType})"
                : Bytes(value, $"{column}[{index}]"),
            _ => $"{column}[{index}]",
        };
    }

    /// <summary>
    /// Reads member <paramref name="k"/>'s lists of records: every record of the batch's lists in one
    /// read of the nested record, into a rented buffer, then each row's range copied out of it.
    /// </summary>
    private static void EmitReadRecordList(SourceWriter w, ValueModel value, int k, string target)
    {
        string nested = value.Element!.CoreType;
        w.Line($"{Vortex}ListColumns<{nested}> lists = columns.ListOf<{nested}>({k});");
        w.Line($"{Vortex}Columns<{nested}> elements = lists.Elements;");
        w.Line("int total = elements.RowCount;");
        w.Line($"{nested}[] all = {Pool}{nested}>.Shared.Rent(total);");
        w.Open("try");
        w.Line($"ReadNested(elements, new global::System.Span<{nested}>(all, 0, total));");
        w.Open("for (int i = 0; i < count; i++)");
        w.Line("(int offset, int length) = lists[i].GetOffsetAndLength(total);");
        string read = $"RecordList{k}(new global::System.ReadOnlySpan<{nested}>(all, offset, length))";
        w.Line(value.IsNullable ? $"{target} = lists.IsValid(i) ? {read} : default({value.MemberType});" : $"{target} = {read};");
        w.Close();
        w.Close();
        w.Open("finally");
        w.Line($"{Pool}{nested}>.Shared.Return(all, {ContainsReferences}{nested}>());");
        w.Close();
    }

    /// <summary>Reads member <paramref name="k"/>'s maps: each row's entries into a dictionary sized for them.</summary>
    private static void EmitReadMap(SourceWriter w, ValueModel value, int k, string target)
    {
        ValueModel key = value.Key!;
        ValueModel item = value.Element!;
        w.Line($"{Vortex}MapColumns<{key.ColumnType}, {item.ColumnType}> maps = columns.MapOf<{key.ColumnType}, {item.ColumnType}>({k});");
        w.Line($"{Vortex}Column<{key.ColumnType}> keys = maps.Keys;");
        w.Line($"{Vortex}Column<{item.ColumnType}> values = maps.Values;");
        string keyRead = EntryRead(w, key, "keys", "keyValues");
        string valueRead = EntryRead(w, item, "values", "valueValues");
        string dictionary = $"global::System.Collections.Generic.Dictionary<{key.MemberType}, {item.MemberType}>";
        w.Open("for (int i = 0; i < count; i++)");
        if (value.IsNullable)
        {
            w.Open("if (!maps.IsValid(i))");
            w.Line($"{target} = default;");
            w.Line("continue;");
            w.Close();
            w.Line();
        }

        w.Line("(int offset, int length) = maps[i].GetOffsetAndLength(keys.Length);");
        w.Line($"{dictionary} map = new {dictionary}(length);");
        w.Open("for (int j = offset; j < offset + length; j++)");
        w.Line($"map[{keyRead}] = {valueRead};");
        w.Close();
        w.Line();
        w.Line($"{target} = map;");
        w.Close();
    }

    /// <summary>
    /// The expression of entry <c>j</c> of a map's keys or values: a number from the column's
    /// values, resolved once before the loop, anything else through its column.
    /// </summary>
    private static string EntryRead(SourceWriter w, ValueModel entry, string column, string span)
    {
        if (entry.IsNumber && !entry.IsNullable)
        {
            w.Line($"global::System.ReadOnlySpan<{entry.UnderlyingType}> {span} = {column}.Values;");
            return entry.Kind == ValueKind.Enum ? $"({entry.MemberType}){span}[j]" : $"{span}[j]";
        }

        return ScalarRead(entry, column, "j");
    }

    /// <summary>Writes member <paramref name="k"/>'s maps: each row's entries, a key and its value, between its map's ends.</summary>
    private static void EmitWriteMap(SourceWriter w, ValueModel value, int k, string source, ref int unique)
    {
        ValueModel key = value.Key!;
        ValueModel item = value.Element!;
        w.Line($"{Vortex}MapColumnsBuilder<{key.ColumnType}, {item.ColumnType}> maps = builder.MapOf<{key.ColumnType}, {item.ColumnType}>({k});");
        w.Line($"{Vortex}ColumnBuilder<{key.ColumnType}> keys = maps.Keys;");
        w.Line($"{Vortex}ColumnBuilder<{item.ColumnType}> values = maps.Values;");
        w.Open("for (int i = 0; i < count; i++)");
        if (value.IsNullable)
        {
            w.Open($"if ({source} is not {{ }} map)");
            w.Line("maps.AppendNull();");
            w.Line("continue;");
            w.Close();
            w.Line();
        }
        else
        {
            w.Line($"var map = {source};");
        }

        w.Line("maps.BeginMap();");
        w.Open($"foreach (global::System.Collections.Generic.KeyValuePair<{key.MemberType}, {item.MemberType}> entry in map)");
        EmitWriteValue(w, key, "keys", "entry.Key", ref unique);
        EmitWriteValue(w, item, "values", "entry.Value", ref unique);
        w.Close();
        w.Line();
        w.Line("maps.EndMap();");
        w.Close();
    }

    /// <summary>A local function that copies one row's records into the container the member declares.</summary>
    private static void EmitRecordListContainer(SourceWriter w, ValueModel list, string name)
    {
        string nested = list.Element!.CoreType;
        w.Open($"static {list.CoreType} {name}(global::System.ReadOnlySpan<{nested}> records)");
        switch (list.Shape)
        {
            case ListShape.List:
                w.Line($"global::System.Collections.Generic.List<{nested}> list = new global::System.Collections.Generic.List<{nested}>(records.Length);");
                w.Line("global::System.Runtime.InteropServices.CollectionsMarshal.SetCount(list, records.Length);");
                w.Line("records.CopyTo(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list));");
                w.Line("return list;");
                break;
            default:
                w.Line($"return {Contain(list, "records.ToArray()")};");
                break;
        }

        w.Close();
    }

    /// <summary>
    /// A local function that copies one list of <paramref name="list"/>'s column into a new array,
    /// or straight into a new <c>List&lt;T&gt;</c> for a member declared as one, so that no array is
    /// copied twice.
    /// </summary>
    private static void EmitReadList(SourceWriter w, ValueModel list, string name)
    {
        ValueModel element = list.Element!;
        bool asList = list.Shape == ListShape.List;
        string returns = asList ? $"global::System.Collections.Generic.List<{element.MemberType}>" : $"{element.MemberType}[]";
        w.Open($"static {returns} {name}({Vortex}Column<{list.ColumnType}> column, {Vortex}Column<{element.ColumnType}> elements, int row)");
        w.Line("(int offset, int length) = column[row].GetOffsetAndLength(elements.Length);");
        bool bulk = element.IsNumber && !element.IsNullable && element.Kind == ValueKind.Scalar;
        if (!asList && bulk)
        {
            w.Line("return elements.Values.Slice(offset, length).ToArray();");
            w.Close();
            return;
        }

        string into;
        if (asList)
        {
            w.Line($"{returns} list = new {returns}(length);");
            w.Line("global::System.Runtime.InteropServices.CollectionsMarshal.SetCount(list, length);");
            w.Line($"global::System.Span<{element.MemberType}> into = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list);");
            into = "into";
            if (bulk)
            {
                w.Line("elements.Values.Slice(offset, length).CopyTo(into);");
                w.Line("return list;");
                w.Close();
                return;
            }
        }
        else
        {
            w.Open("if (length == 0)");
            w.Line("return [];");
            w.Close();
            w.Line();
            // Every element is written below, and an array of arrays has no `new T[n]` spelling
            // that holds for any T: `new int[][n]` is not C#.
            w.Line($"{element.MemberType}[] list = global::System.GC.AllocateUninitializedArray<{element.MemberType}>(length);");
            into = "list";
        }

        string read;
        if (element.IsNumber && !element.IsNullable)
        {
            w.Line($"global::System.ReadOnlySpan<{element.UnderlyingType}> values = elements.Values;");
            read = $"({element.MemberType})values[offset + j]";
        }
        else if (element.Kind == ValueKind.List)
        {
            w.Line($"{Vortex}Column<{element.Element!.ColumnType}> inner = elements.Elements;");
            string call = Contain(element, $"{name}_(elements, inner, offset + j)");
            read = element.IsNullable
                ? $"elements.IsValid(offset + j) ? {call} : default({element.MemberType})"
                : call;
        }
        else
        {
            read = ScalarRead(element, "elements", "offset + j");
        }

        w.Open("for (int j = 0; j < length; j++)");
        w.Line($"{into}[j] = {read};");
        w.Close();
        w.Line();
        w.Line("return list;");
        w.Close();
        if (element.Kind == ValueKind.List)
        {
            w.Line();
            EmitReadList(w, element, name + "_");
        }
    }

    /// <summary>
    /// A list read into an array, or into a list for a <c>List&lt;T&gt;</c>, as the member's
    /// container: an array is already every interface it implements, and an immutable array wraps it
    /// without a copy.
    /// </summary>
    private static string Contain(ValueModel list, string read) => list.Shape switch
    {
        ListShape.ReadOnlyMemory => $"new global::System.ReadOnlyMemory<{list.Element!.MemberType}>({read})",
        ListShape.Memory => $"new global::System.Memory<{list.Element!.MemberType}>({read})",
        ListShape.ImmutableArray => $"global::System.Runtime.InteropServices.ImmutableCollectionsMarshal.AsImmutableArray({read})",
        _ => read,
    };

    /// <summary>A binary value's borrowed bytes copied into the buffer the member declares.</summary>
    private static string Bytes(ValueModel value, string span) => value.Shape switch
    {
        ListShape.Array => $"{span}.ToArray()",
        ListShape.Memory => $"new global::System.Memory<byte>({span}.ToArray())",
        _ => $"new global::System.ReadOnlyMemory<byte>({span}.ToArray())",
    };

    /// <summary>The span over a binary value's bytes, or over a list's elements, whatever holds them.</summary>
    private static string SpanOf(ValueModel value, string element, string source) => value.Shape switch
    {
        ListShape.ReadOnlyMemory or ListShape.Memory => $"{source}.Span",
        ListShape.Array => $"new global::System.ReadOnlySpan<{element}>({source})",
        ListShape.List => $"global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({source})",
        _ => $"{source}.AsSpan()",
    };

    private static void EmitWriteRows(SourceWriter w, RecordModel model)
    {
        string signature = $"void {(model.Names.ExplicitWriteRows ? Vortex + "IVortexRecord<" + model.FullName + ">." : string.Empty)}WriteRows({Vortex}ColumnsBuilder<{model.FullName}> builder, global::System.ReadOnlySpan<{model.FullName}> rows)";
        if (model.Names.ExplicitWriteRows)
        {
            w.Open("static " + signature);
        }
        else
        {
            w.Line("/// <inheritdoc/>");
            w.Open((model.Names.HidesWriteRows ? "public new static " : "public static ") + signature);
        }

        w.Line("int count = rows.Length;");
        bool nested = false;
        int unique = 0;
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            string source = "rows[i]." + RecordAnalysis.Escape(member.Name);
            w.Line("{");
            w.Indent();
            if (value.Kind == ValueKind.Record)
            {
                nested = true;
                EmitWriteNested(w, value, k, source);
            }
            else if (value.IsRecordList)
            {
                nested = true;
                EmitWriteRecordList(w, value, k, source);
            }
            else if (value.Kind == ValueKind.Map)
            {
                EmitWriteMap(w, value, k, source, ref unique);
            }
            else if (value.IsNumber && !value.IsNullable)
            {
                w.Line($"{Vortex}ColumnBuilder<{value.ColumnType}> column = builder.Column<{value.ColumnType}>({k});");
                w.Line($"global::System.Span<{value.ColumnType}> span = column.GetSpan(count);");
                Loop(w, value.Kind == ValueKind.Enum ? $"span[i] = ({value.UnderlyingType}){source};" : $"span[i] = {source};");
                w.Line();
                w.Line("column.Advance(count);");
            }
            else
            {
                w.Line($"{Vortex}ColumnBuilder<{value.ColumnType}> column = builder.Column<{value.ColumnType}>({k});");
                w.Open("for (int i = 0; i < count; i++)");
                EmitWriteValue(w, value, "column", source, ref unique);
                w.Close();
            }

            w.Close();
            if (k < model.Members.Count - 1 || nested)
            {
                w.Line();
            }
        }

        if (nested)
        {
            w.Line($"static void WriteNested<TNested>({Vortex}ColumnsBuilder<TNested> builder, global::System.ReadOnlySpan<TNested> rows)");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.WriteRows(builder, rows);");
        }

        w.Close();
    }

    private static void EmitWriteNested(SourceWriter w, ValueModel value, int k, string source)
    {
        string nested = value.CoreType;
        string span = $"new global::System.ReadOnlySpan<{nested}>(nested, 0, ";
        if (value.IsNullable)
        {
            w.Line($"{Vortex}ColumnsBuilder<{nested}> nestedBuilder = builder.Struct<{nested}>({k});");
        }

        w.Line($"{nested}[] nested = {Pool}{nested}>.Shared.Rent(count);");
        w.Open("try");
        if (value.IsNullable)
        {
            w.Line("int run = 0;");
            w.Open("for (int i = 0; i < count; i++)");
            w.Open($"if ({source} is {{ }} value)");
            w.Line("nested[run++] = value;");
            w.Line("continue;");
            w.Close();
            w.Line();
            w.Open("if (run > 0)");
            w.Line($"WriteNested(nestedBuilder, {span}run));");
            w.Line("run = 0;");
            w.Close();
            w.Line();
            w.Line("nestedBuilder.AppendNull();");
            w.Close();
            w.Line();
            w.Open("if (run > 0)");
            w.Line($"WriteNested(nestedBuilder, {span}run));");
            w.Close();
        }
        else
        {
            Loop(w, $"nested[i] = {source};");
            w.Line();
            w.Line($"WriteNested(builder.Struct<{nested}>({k}), {span}count));");
        }

        w.Close();
        w.Open("finally");
        w.Line($"{Pool}{nested}>.Shared.Return(nested, {ContainsReferences}{nested}>());");
        w.Close();
    }

    /// <summary>Writes member <paramref name="k"/>'s lists of records: each row's records in one write of the nested record, between its list's ends.</summary>
    private static void EmitWriteRecordList(SourceWriter w, ValueModel value, int k, string source)
    {
        string nested = value.Element!.CoreType;
        w.Line($"{Vortex}ListColumnsBuilder<{nested}> lists = builder.ListOf<{nested}>({k});");
        w.Line($"{Vortex}ColumnsBuilder<{nested}> elements = lists.Elements;");
        w.Open("for (int i = 0; i < count; i++)");
        if (value.IsNullable)
        {
            w.Open($"if ({source} is not {{ }} records)");
            w.Line("lists.AppendNull();");
            w.Line("continue;");
            w.Close();
            w.Line();
        }
        else
        {
            w.Line($"var records = {source};");
        }

        string span = value.Shape == ListShape.Sequence
            ? $"global::System.Linq.Enumerable.ToArray(records)"
            : SpanOf(value, nested, "records");
        w.Line("lists.BeginList();");
        w.Line($"WriteNested(elements, {span});");
        w.Line("lists.EndList();");
        w.Close();
    }

    /// <summary>Appends <paramref name="source"/>, one value of <paramref name="value"/>'s type, to <paramref name="builder"/>.</summary>
    private static void EmitWriteValue(SourceWriter w, ValueModel value, string builder, string source, ref int unique)
    {
        if (value.Kind == ValueKind.Enum)
        {
            w.Line($"{builder}.Append(({value.ColumnType}){source});");
            return;
        }

        switch (value.Kind == ValueKind.List ? (ScalarKind?)null : value.Scalar)
        {
            case ScalarKind.Utf8 when value.IsNullable:
                string text = "text" + unique++;
                IfPresent(w, builder, source, text, $"{builder}.Append(global::System.MemoryExtensions.AsSpan({text}));");
                return;
            case ScalarKind.Utf8:
                w.Line($"{builder}.Append(global::System.MemoryExtensions.AsSpan({source}));");
                return;
            case ScalarKind.Binary when value.IsNullable:
                string bytes = "bytes" + unique++;
                IfPresent(w, builder, source, bytes, $"{builder}.Append({SpanOf(value, "byte", bytes)});");
                return;
            case ScalarKind.Binary:
                w.Line($"{builder}.Append({SpanOf(value, "byte", source)});");
                return;
            case null:
                break;
            default:
                w.Line($"{builder}.Append({source});");
                return;
        }

        if (value.IsNullable)
        {
            string list = "list" + unique++;
            w.Open($"if ({source} is {{ }} {list})");
            EmitWriteList(w, value, builder, list, ref unique);
            w.Close();
            w.Open("else");
            w.Line($"{builder}.AppendNull();");
            w.Close();
            return;
        }

        EmitWriteList(w, value, builder, source, ref unique);
    }

    private static void IfPresent(SourceWriter w, string builder, string source, string name, string append)
    {
        w.Open($"if ({source} is {{ }} {name})");
        w.Line(append);
        w.Close();
        w.Open("else");
        w.Line($"{builder}.AppendNull();");
        w.Close();
    }

    private static void EmitWriteList(SourceWriter w, ValueModel list, string builder, string source, ref int unique)
    {
        ValueModel element = list.Element!;
        if (list.ElementsAsDeclared && list.Shape != ListShape.Sequence)
        {
            w.Line($"{builder}.Append({SpanOf(list, element.MemberType, source)});");
            return;
        }

        string elements = "elements" + unique++;
        string item = "item" + unique++;
        w.Line($"{builder}.BeginList();");
        w.Line($"var {elements} = {builder}.Elements;");
        w.Open($"foreach ({element.MemberType} {item} in {(list.Shape == ListShape.Sequence ? source : SpanOf(list, element.MemberType, source))})");
        EmitWriteValue(w, element, elements, item, ref unique);
        w.Close();
        w.Line();
        w.Line($"{builder}.EndList();");
    }

    private static void EmitColumnNames(SourceWriter w, RecordModel model)
    {
        w.Line("/// <summary>The name of each member's column, for the options that name a column.</summary>");
        w.Open($"public {(model.Names.HidesColumnNames ? "new " : string.Empty)}static class ColumnNames");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            if (k > 0)
            {
                w.Line();
            }

            w.Line($"/// <summary>The column of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line($"public const string {RecordAnalysis.Escape(member.Name)} = {SymbolDisplay.FormatLiteral(member.ColumnName, quote: true)};");
        }

        w.Close();
    }

    private static void EmitHelpers(SourceWriter w, RecordModel model)
    {
        if (model.NeedsSchemaHelper)
        {
            w.Line();
            w.Line($"private static {Vortex}VortexSchema VortexSchemaOf<TNested>()");
            w.Line($"    where TNested : {Vortex}IVortexRecord<TNested> => TNested.Schema;");
        }

        if (model.NeedsExtensionHelper)
        {
            w.Line();
            w.Line($"private static {Vortex}VortexType VortexExtensionTypeOf<TExtension>()");
            w.Line($"    where TExtension : {Vortex}IVortexExtension<TExtension> => {Vortex}VortexType.Extension(TExtension.Id, TExtension.StorageType);");
        }
    }

    private static void EmitExtensions(SourceWriter w, RecordModel model)
    {
        GeneratedNames names = model.Names;
        string record = model.FullName;
        w.Line($"/// <summary>The members of <see cref=\"{record}\"/> as symbols in a scan's lambdas, as columns of a delivered batch, and as builders of a writer.</summary>");
        w.Open($"{model.ExtensionsAccessibility} static class {model.ExtensionsName}");

        w.Open($"extension({Vortex}Probe<{record}> {names.ProbeName})");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            if (value.IsRecordList || value.Kind == ValueKind.Map)
            {
                // No filter compares a list of records or a map, so neither has a symbol.
                continue;
            }

            Separate(w, k);
            w.Line($"/// <summary>The symbol of <see cref=\"{Cref(member)}\"/>, for the lambdas of a scan.</summary>");
            w.Line(value.Kind == ValueKind.Record
                ? $"public {Vortex}Probe<{value.CoreType}> {RecordAnalysis.Escape(member.Name)} => {names.ProbeName}.Struct<{value.CoreType}>({k});"
                : $"public {Vortex}Sym<{value.SymbolType}> {RecordAnalysis.Escape(member.Name)} => {names.ProbeName}.Column<{value.SymbolType}>({k});");
        }

        w.Close();
        w.Line();

        w.Open($"extension({Vortex}Columns<{record}> {names.ColumnsName})");
        List<string> parameters = [];
        List<string> assignments = [];
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            string type = ColumnsType(member.Value);
            string access = ColumnsAccess(member.Value, names.ColumnsName, k);
            Separate(w, k);
            w.Line($"/// <summary>The column of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line($"public {type} {RecordAnalysis.Escape(member.Name)} => {access};");
            parameters.Add($"out {type} {names.DeconstructNames[k]}");
            assignments.Add($"{names.DeconstructNames[k]} = {access};");
        }

        w.Line();
        w.Line("/// <summary>Every member's column, in order, for <c>await foreach (var (...) in scan)</c>.</summary>");
        w.Open($"public void Deconstruct({string.Join(", ", parameters)})");
        foreach (string assignment in assignments)
        {
            w.Line(assignment);
        }

        w.Close();
        w.Close();
        w.Line();

        w.Open($"extension({Vortex}ColumnsBuilder<{record}> {names.BuilderName})");
        for (int k = 0; k < model.Members.Count; k++)
        {
            MemberModel member = model.Members[k];
            ValueModel value = member.Value;
            Separate(w, k);
            w.Line($"/// <summary>The builder of <see cref=\"{Cref(member)}\"/>.</summary>");
            w.Line(value.Kind == ValueKind.Record
                ? $"public {Vortex}ColumnsBuilder<{value.CoreType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.Struct<{value.CoreType}>({k});"
                : value.IsRecordList
                    ? $"public {Vortex}ListColumnsBuilder<{value.Element!.CoreType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.ListOf<{value.Element.CoreType}>({k});"
                    : value.Kind == ValueKind.Map
                        ? $"public {Vortex}MapColumnsBuilder<{value.Key!.ColumnType}, {value.Element!.ColumnType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.MapOf<{value.Key.ColumnType}, {value.Element.ColumnType}>({k});"
                        : $"public {Vortex}ColumnBuilder<{value.ColumnType}> {RecordAnalysis.Escape(member.Name)} => {names.BuilderName}.Column<{value.ColumnType}>({k});");
        }

        w.Close();
        w.Close();
    }

    private static string ColumnsType(ValueModel value) =>
        value.Kind == ValueKind.Record ? $"{Vortex}Columns<{value.CoreType}>"
        : value.IsRecordList ? $"{Vortex}ListColumns<{value.Element!.CoreType}>"
        : value.Kind == ValueKind.Map ? $"{Vortex}MapColumns<{value.Key!.ColumnType}, {value.Element!.ColumnType}>"
        : $"{Vortex}Column<{value.ColumnType}>";

    private static string ColumnsAccess(ValueModel value, string receiver, int k) =>
        value.Kind == ValueKind.Record ? $"{receiver}.Struct<{value.CoreType}>({k})"
        : value.IsRecordList ? $"{receiver}.ListOf<{value.Element!.CoreType}>({k})"
        : value.Kind == ValueKind.Map ? $"{receiver}.MapOf<{value.Key!.ColumnType}, {value.Element!.ColumnType}>({k})"
        : $"{receiver}.Column<{value.ColumnType}>({k})";

    private static void Separate(SourceWriter w, int k)
    {
        if (k > 0)
        {
            w.Line();
        }
    }

    private static string Cref(MemberModel member) => member.DeclaringType + "." + RecordAnalysis.Escape(member.Name);
}
